/**
 * This file was generated by Create. You may edit it but doing so may cause
 * issues in your app.
 */
async function upload({
  url,
  buffer,
  base64
}) {
  const response = await fetch(`https://api.create.xyz/v0/upload`, {
    method: "POST",
    headers: {
      "Content-Type": buffer ? "application/octet-stream" : "application/json"
    },
    body: buffer ? buffer : JSON.stringify({ base64, url })
  });
  const data = await response.json();
  return {
    url: data.url,
    mimeType: data.mimeType || null
  };
}
export { upload };
export default upload;
import sql from "@/app/api/utils/sql";

// GET - List appointments with optional filtering
export async function GET(request) {
  try {
    const url = new URL(request.url);
    const campaignId = url.searchParams.get('campaign_id');
    const status = url.searchParams.get('status');
    const limit = parseInt(url.searchParams.get('limit')) || 50;

    let query = `
      SELECT 
        a.*,
        c.name as campaign_name
      FROM appointments a
      LEFT JOIN campaigns c ON a.campaign_id = c.id
      WHERE 1=1
    `;
    const values = [];
    let paramCount = 1;

    if (campaignId) {
      query += ` AND a.campaign_id = $${paramCount}`;
      values.push(campaignId);
      paramCount++;
    }

    if (status) {
      query += ` AND a.status = $${paramCount}`;
      values.push(status);
      paramCount++;
    }

    query += ` ORDER BY a.scheduled_for ASC LIMIT $${paramCount}`;
    values.push(limit);

    const appointments = await sql(query, values);

    return Response.json({ appointments });
  } catch (error) {
    console.error('Error fetching appointments:', error);
    return Response.json({ error: 'Failed to fetch appointments' }, { status: 500 });
  }
}

// POST - Create new appointment
export async function POST(request) {
  try {
    const body = await request.json();
    const { campaign_id, customer_name, phone, scheduled_for, agent_name, notes } = body;

    if (!customer_name || !phone || !scheduled_for) {
      return Response.json({ 
        error: 'Customer name, phone, and scheduled time are required' 
      }, { status: 400 });
    }

    const [appointment] = await sql`
      INSERT INTO appointments (campaign_id, customer_name, phone, scheduled_for, agent_name, notes)
      VALUES (${campaign_id || null}, ${customer_name}, ${phone}, ${scheduled_for}, ${agent_name || null}, ${notes || null})
      RETURNING *
    `;

    // Update campaign appointment count if campaign_id provided
    if (campaign_id) {
      await sql`
        UPDATE campaigns 
        SET appointments_booked = appointments_booked + 1,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ${campaign_id}
      `;
    }

    return Response.json({ appointment });
  } catch (error) {
    console.error('Error creating appointment:', error);
    return Response.json({ error: 'Failed to create appointment' }, { status: 500 });
  }
}
/**
 * This file was generated by Create. You may edit it but doing so may cause
 * issues in your app.
 */
import { getToken } from '@auth/core/jwt';
export async function GET(request) {
  const [token, jwt] = await Promise.all([
    getToken({
      req: request,
      secret: process.env.AUTH_SECRET,
      secureCookie: process.env.AUTH_URL.startsWith('https'),
      raw: true,
    }),
    getToken({
      req: request,
      secret: process.env.AUTH_SECRET,
      secureCookie: process.env.AUTH_URL.startsWith('https'),
    }),
  ]);

  if (!jwt) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }

  return new Response(
    JSON.stringify({
      jwt: token,
      user: {
        id: jwt.sub,
        email: jwt.email,
        name: jwt.name,
      },
    }),
    {
      headers: {
        'Content-Type': 'application/json',
      },
    }
  );
}